### ISSUE TITLE
Settings provider detection problem

### ISSUE THREAD

**Issue by BTopbas** [i96751414/script.flix.magneto#1]
Here is problem:
My settings.xml:
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<settings>
    <!-- General -->
    <category label="30000">
    </category>
    <!-- Providers -->
    <category label="30001">
		<setting id="1" type="bool" label="testex" default="<true|false>"/>
    </category>
</settings>
```
My providers.json:
```
[
  {
    "name": "testex",
    "base_url": "https://torrentapi.org/pubapi_v2.php",
    "results_parser": {
      "url": "?mode=search&search_string={query:q}&format=json_extended&app_id=script.elementum.burst&token=36gja8ncme",
      "type": "json",
      "rows": "./torrent_results",
      "data": {
        "title": "./title/text()",
        "size": "./size/text()",
        "seeds": "./seeders/text()",
        "leeches": "./leechers/text()",
        "magnet": "./download/text()"
      }
    },
    "keywords": {
      "movie": "{title} {year}",
      "show": "{title}",
      "season": "{title} S{season:02}",
      "episode": "{title} S{season:02}E{episode:02}"
    },
    "attributes": {
      "color": "FFF14E13",
      "icon": "provider_icons/example.png"
    }
  }
]
```

DEBUG <general>: found key /userdata/addon_data/script.flix.magneto/settings.xml
2020-07-19 19:40:46.931 T:1541736   DEBUG <CAddonSettings[script.flix.magneto]>: loading setting values
2020-07-19 19:40:46.931 T:1541736   DEBUG <CSettingsManager>: requested setting (<provider.id>) was not found.
2020-07-19 19:40:46.931 T:1541736   DEBUG <CAddonSettings[script.flix.magneto]>: failed to find definition for setting <provider.id>. Creating a setting on-the-fly...
2020-07-19 19:40:46.931 T:1541736   DEBUG <CSettingsManager>: requested setting (testex) **was not found.**

If I remove [ ] array in providers.json this is fixes "was not found" error but another thing is happened:

```
ERROR <general>: [script.flix.magneto] Failed running method 'search_movie' with data 'eyJhcmdzIjogWyI1MTQyMDciLCAiXHUwNDEyXHUwNDQyXHUwNDNlXHUwNDQwXHUwNDM2XHUwNDM1XHUwNDNkXHUwNDM4XHUwNDM1IiwgeyJjbCI6ICJJbnZhc2lcdTAwZjNuIEVsIGZpbiBkZSBsb3MgdGllbXBvcyIsICJkZSI6ICJBVFRSQUNUSU9OIDIgLSBJTlZBU0lPTiIsICJmciI6ICJQcml0eWF6aGVuaWUgMiIsICJrciI6ICJcdWM1YjRcdWQyYjhcdWI3OTlcdWMxNTggMiIsICJybyI6ICJJbnZhemlhIiwgInJ1IjogIlx1MDQxZlx1MDQ0MFx1MDQzOFx1MDQ0Mlx1MDQ0Zlx1MDQzNlx1MDQzNVx1MDQzZFx1MDQzOFx1MDQzNSAyIiwgInVzIjogIkF0dHJhY3Rpb24gMiJ9XSwgImt3YXJncyI6IHsieWVhciI6IDIwMjB9fQ==': string indices must be integers
                                                   Traceback (most recent call last):
                                                     File "/private/var/mobile/Containers/Data/Application/CFF0B279-F2D8-4F4D-A516-F538BE664656/Library/Caches/Kodi/addons/plugin.video.flix/lib/api/flix/provider.py", line 247, in register
                                                       value = self._methods[method](*data.get("args", []), **data.get("kwargs", {}))
                                                     File "/private/var/mobile/Containers/Data/Application/CFF0B279-F2D8-4F4D-A516-F538BE664656/Library/Caches/Kodi/addons/script.flix.magneto/lib/provider.py", line 128, in search_movie
                                                       return perform_search("movie", dict(tmdb_id=tmdb_id, title=Title(title, titles), year=year or ""))
                                                     File "/private/var/mobile/Containers/Data/Application/CFF0B279-F2D8-4F4D-A516-F538BE664656/Library/Caches/Kodi/addons/script.flix.magneto/lib/provider.py", line 99, in perform_search
                                                       scrapers = [s for s in Scraper.get_scrapers(os.path.join(ADDON_PATH, "resources", "providers.json"))
                                                     File "/private/var/mobile/Containers/Data/Application/CFF0B279-F2D8-4F4D-A516-F538BE664656/Library/Caches/Kodi/addons/script.flix.magneto/lib/scraper.py", line 110, in get_scrapers
                                                       return [Scraper.from_data(data) for data in json.load(f)]
                                                     File "/private/var/mobile/Containers/Data/Application/CFF0B279-F2D8-4F4D-A516-F538BE664656/Library/Caches/Kodi/addons/script.flix.magneto/lib/scraper.py", line 110, in <listcomp>
                                                       return [Scraper.from_data(data) for data in json.load(f)]
                                                     File "/private/var/mobile/Containers/Data/Application/CFF0B279-F2D8-4F4D-A516-F538BE664656/Library/Caches/Kodi/addons/script.flix.magneto/lib/scraper.py", line 115, in from_data
                                                       data["name"], data["base_url"], ResultsParser(**data["results_parser"]),
                                                   TypeError: string indices must be integers
```

Both stations return with "NO RESULT." 
In second station "**Failed running method 'search_movie' with data 'eyJhcmdzIjogWyI1MTQyMDciLCAiXHUwNDE...'**" maybe https://github.com/i96751414/plugin.video.flix/issues/4 this changes cause this ?

**Comment by i96751414** [comment]
Please note that the settings id must match the provider json name in lowercase with spaces replaced by dots. I will add that to the documentário later.

**Comment by BTopbas** [comment]
> Please note that the settings id must match the provider json name in lowercase with spaces replaced by dots. I will add that to the documentário later. Also, default needs to be either true or false.

So settings sections will be like this? :
`<setting id="testex" type="bool" label="testex" default="true"/>`

**Comment by i96751414** [comment]
Exactly

**Comment by BTopbas** [comment]
> Exactly

Worked! I am very close!! Now I can't parse JSON values. I have returned JSON like this:

```
{
   "torrent_results":[
      {
         "title":"item_title",
         "size":"item_size",
         "download":"download_magnet"
      },
      {
         "title":"item_title",
         "category":"item_category",
         "download":"download_magnet"
      }
   ]
}
```
And my provider parse section like this:

```
"type": "json",
      "rows": "./torrent_results",
      "data": {
        "title": "./title/text()",
        "size": "./size/text()",
        "magnet": "./download/text()"
      }
```
But its return this error `Failed running scraper testex: 'NoneType' object has no attribute 'text'`
I tried different combinations but always fail.

**Comment by BTopbas** [comment]
Okey. Now works like a charm!
```
"type": "json",
      "rows": ".//torrent_results/",
      "data": {
        "title": ".title/text()",
        "size": ".size/text()",
        "magnet": ".download/text()"
      }
```
